import { useCalculator } from '@/hooks/useCalculator';
import { KPIDashboard } from './KPIDashboard';
import { InputForm } from './InputForm';
import { KeyMetricsPanel } from './KeyMetricsPanel';
import { Charts } from './Charts';
import { SavedCalculation } from '@/types/calculator';
import { Share2, Save, Sparkles, FileDown } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { exportDealPdf } from '@/lib/exportPdf';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { useState, useRef } from 'react';

interface CalculatorTabProps {
  calculator: ReturnType<typeof useCalculator>;
  onSave: (name: string) => void;
  onOpenCoach: () => void;
}

export function CalculatorTab({ calculator, onSave, onOpenCoach }: CalculatorTabProps) {
  const { state, outputs, updateField } = calculator;
  const [saveOpen, setSaveOpen] = useState(false);
  const [saveName, setSaveName] = useState('');
  const [exporting, setExporting] = useState(false);
  const chartsRef = useRef<HTMLDivElement>(null);

  const handleExportPdf = async () => {
    setExporting(true);
    try {
      await exportDealPdf(state, outputs, chartsRef.current);
    } finally {
      setExporting(false);
    }
  };

  const handleShare = () => {
    const text = `CashFlow Analysis
━━━━━━━━━━━━━━━
Purchase Price: $${state.purchasePrice.toLocaleString()}
Down Payment: ${state.downPaymentPercent}% ($${outputs.downPaymentAmount.toLocaleString()})
Loan Amount: $${outputs.loanAmount.toLocaleString()}
Monthly Rent: $${(state.rentPerUnit * state.numberOfUnits).toLocaleString()}
Vacancy: ${state.vacancyRate}%

Results:
Monthly Cash Flow: $${outputs.monthlyCashFlow.toFixed(0)}
CoC ROI: ${outputs.cashOnCashROI.toFixed(2)}%
Cap Rate: ${outputs.capRate.toFixed(2)}%
Total ROI: ${outputs.totalROI.toFixed(2)}%
Deal Rating: ${outputs.dealRating}

Generated by CashFlow`;

    navigator.clipboard.writeText(text).then(() => {
      toast.success('Analysis copied to clipboard!');
    }).catch(() => {
      toast.error('Could not copy to clipboard');
    });
  };

  const handleSave = () => {
    if (!saveName.trim()) return;
    onSave(saveName.trim());
    setSaveOpen(false);
    setSaveName('');
    toast.success('Calculation saved!');
  };

  return (
    <div className="p-4 md:p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <h1 className="text-xl md:text-2xl font-bold text-foreground">Investment Calculator</h1>
        <div className="flex gap-2 items-center">
          <button
            onClick={onOpenCoach}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-primary/10 text-primary border border-primary/20 hover:bg-primary/20 transition-colors text-sm font-semibold"
          >
            <Sparkles className="w-4 h-4" />
            Deal Advisor
          </button>
          <Button variant="outline" size="sm" onClick={handleExportPdf} disabled={exporting}>
            <FileDown className="w-4 h-4 mr-1.5" /> {exporting ? 'Exporting…' : 'Export PDF'}
          </Button>
          <Button variant="outline" size="sm" onClick={handleShare}>
            <Share2 className="w-4 h-4 mr-1.5" /> Share
          </Button>
          <Button size="sm" onClick={() => setSaveOpen(true)}>
            <Save className="w-4 h-4 mr-1.5" /> Save
          </Button>
        </div>
      </div>

      {/* KPI Dashboard */}
      <KPIDashboard outputs={outputs} isDIY={state.isDIY} onToggleDIY={v => updateField('isDIY', v)} />

      {/* Two Column: Form + Metrics */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <InputForm state={state} updateField={updateField} />
        </div>
        <div>
          <KeyMetricsPanel outputs={outputs} />
        </div>
      </div>

      {/* Charts */}
      <div ref={chartsRef}>
        <Charts outputs={outputs} appreciationRate={state.appreciationRate} />
      </div>

      {/* Save Dialog */}
      <Dialog open={saveOpen} onOpenChange={setSaveOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Save Calculation</DialogTitle>
          </DialogHeader>
          <input
            type="text"
            maxLength={60}
            value={saveName}
            onChange={e => setSaveName(e.target.value)}
            placeholder="e.g. 123 Main St — 3BR Duplex"
            className="w-full h-10 rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
            onKeyDown={e => e.key === 'Enter' && handleSave()}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setSaveOpen(false)}>Cancel</Button>
            <Button onClick={handleSave} disabled={!saveName.trim()}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
