import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { CalculatorState, CalculatorOutputs } from '@/types/calculator';

const PAGE_W = 216; // letter width mm
const PAGE_H = 279; // letter height mm
const MARGIN = 14;
const CONTENT_W = PAGE_W - MARGIN * 2;

function fmt$(val: number): string {
  const abs = Math.abs(val);
  const sign = val < 0 ? '-' : '';
  return sign + '$' + abs.toLocaleString(undefined, { maximumFractionDigits: 0 });
}

function fmtPct(val: number): string {
  return val.toFixed(2) + '%';
}

function row(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  w: number,
  shade: boolean,
  negative = false,
) {
  if (shade) {
    doc.setFillColor(248, 249, 250);
    doc.rect(x, y - 4, w, 7, 'F');
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(90, 90, 100);
  doc.text(label, x + 3, y);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(negative ? 185 : 30, negative ? 40 : 30, negative ? 40 : 45);
  doc.text(value, x + w - 3, y, { align: 'right' });
  doc.setDrawColor(220, 220, 228);
  doc.setLineWidth(0.2);
  doc.line(x, y + 3, x + w, y + 3);
}

function sectionHeader(doc: jsPDF, title: string, x: number, y: number, w: number) {
  doc.setFillColor(30, 41, 59);
  doc.rect(x, y - 4.5, w, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(title.toUpperCase(), x + 3, y);
}

function pageHeader(doc: jsPDF, label: string) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, PAGE_W, 28, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('Deal Wise Rent', MARGIN, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(148, 163, 184);
  doc.text('Rental Deal Analysis', MARGIN, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text(label, PAGE_W - MARGIN, 13, { align: 'right' });
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(dateStr, PAGE_W - MARGIN, 20, { align: 'right' });
}

function pageFooter(doc: jsPDF) {
  const footerY = PAGE_H - 10;
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, footerY - 3, PAGE_W - MARGIN, footerY - 3);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Deal Wise Rent · For informational purposes only. Not financial advice.', MARGIN, footerY);
  doc.text(dateStr, PAGE_W - MARGIN, footerY, { align: 'right' });
}

export async function exportDealPdf(
  state: CalculatorState,
  outputs: CalculatorOutputs,
  chartsEl: HTMLElement | null = null,
) {
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });

  // ── Page 1 Header ────────────────────────────────────────────
  pageHeader(doc, 'DEAL ANALYSIS REPORT');

  // ── Deal Rating pill ─────────────────────────────────────────
  let ratingBg: [number, number, number] = [22, 163, 74];
  if (outputs.dealRatingColor === 'warning') ratingBg = [202, 138, 4];
  if (outputs.dealRatingColor === 'destructive') ratingBg = [220, 38, 38];

  doc.setFillColor(...ratingBg);
  doc.roundedRect(MARGIN, 33, 36, 8, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text(outputs.dealRating.toUpperCase(), MARGIN + 18, 38.5, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 110);
  doc.text('Deal Rating', MARGIN + 39, 38.5);

  if (state.isDIY) {
    doc.setFillColor(59, 130, 246);
    doc.roundedRect(MARGIN + 75, 33, 22, 8, 2, 2, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(255, 255, 255);
    doc.text('DIY MODE', MARGIN + 86, 38.5, { align: 'center' });
  }

  // ── KPI Cards ────────────────────────────────────────────────
  const kpiY = 48;
  const cardW = (CONTENT_W - 5 * 2) / 3;
  const cardH = 18;
  const gap = (CONTENT_W - cardW * 3) / 2;

  const kpis = [
    { label: 'Monthly Cash Flow', value: fmt$(outputs.monthlyCashFlow), neg: outputs.monthlyCashFlow < 0 },
    { label: 'Cash-on-Cash ROI', value: fmtPct(outputs.cashOnCashROI), neg: outputs.cashOnCashROI < 0 },
    { label: 'Cap Rate', value: fmtPct(outputs.capRate), neg: outputs.capRate < 0 },
    { label: 'Total ROI (Yr 1)', value: fmtPct(outputs.totalROI), neg: outputs.totalROI < 0 },
    { label: 'Annual Cash Flow', value: fmt$(outputs.annualCashFlow), neg: outputs.annualCashFlow < 0 },
    { label: 'Monthly Mortgage', value: fmt$(outputs.monthlyMortgage), neg: false },
  ];

  kpis.forEach((kpi, i) => {
    const col = i % 3;
    const rowIdx = Math.floor(i / 3);
    const cx = MARGIN + col * (cardW + gap);
    const cy = kpiY + rowIdx * (cardH + 3);
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.roundedRect(cx, cy, cardW, cardH, 2, 2, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.label.toUpperCase(), cx + 3, cy + 5.5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(kpi.neg ? 185 : 15, kpi.neg ? 40 : 23, kpi.neg ? 40 : 42);
    doc.text(kpi.value, cx + 3, cy + 14);
  });

  // ── Financial Breakdown ──────────────────────────────────────
  let y = kpiY + 2 * (cardH + 3) + 10;
  sectionHeader(doc, 'Financial Breakdown', MARGIN, y, CONTENT_W);
  y += 7;

  const breakdownRows: [string, number, boolean][] = [
    ['Gross Rental Income (Annual)', outputs.grossRentalIncome, false],
    ['Effective Gross Income (after vacancy)', outputs.effectiveGrossIncome, false],
    ['Total Operating Expenses', -outputs.totalOperatingExpenses, true],
    ['Net Operating Income', outputs.netOperatingIncome, outputs.netOperatingIncome < 0],
    ['Annual Debt Service', -outputs.annualDebtService, true],
    ['Annual Cash Flow', outputs.annualCashFlow, outputs.annualCashFlow < 0],
    ['Monthly Cash Flow', outputs.monthlyCashFlow, outputs.monthlyCashFlow < 0],
  ];

  breakdownRows.forEach(([label, val, neg], i) => {
    const isBold = i >= breakdownRows.length - 2;
    if (isBold) {
      doc.setFont('helvetica', 'bold');
      doc.setFillColor(240, 243, 248);
      doc.rect(MARGIN, y - 4, CONTENT_W, 7, 'F');
    }
    row(doc, label, fmt$(val), MARGIN, y, CONTENT_W, !isBold && i % 2 === 1, neg);
    if (isBold) doc.setFont('helvetica', 'normal');
    y += 7;
  });

  // ── Investment Summary row ───────────────────────────────────
  y += 3;
  const summaryItems = [
    ['Cash Invested', fmt$(outputs.cashInvested)],
    ['Loan Amount', fmt$(outputs.loanAmount)],
    ['Down Payment', fmt$(outputs.downPaymentAmount)],
    ['Yr 1 Principal Paid', fmt$(outputs.principalPaidYear1)],
  ];
  const sumW = CONTENT_W / 4;
  summaryItems.forEach(([label, val], i) => {
    const sx = MARGIN + i * sumW;
    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.rect(sx, y, sumW - 1, 14, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(label.toUpperCase(), sx + 3, y + 5.5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(val, sx + 3, y + 12);
  });
  y += 22;

  // ── Two-column: Inputs ───────────────────────────────────────
  const colW = (CONTENT_W - 5) / 2;

  sectionHeader(doc, 'Purchase & Financing', MARGIN, y, colW);
  y += 7;
  const leftRows: [string, string][] = [
    ['Purchase Price', fmt$(state.purchasePrice)],
    ['Improvements', fmt$(state.improvements)],
    ['Closing Costs', fmt$(state.closingCosts)],
    ['Down Payment', `${state.downPaymentPercent}%`],
    ['Interest Rate', `${state.interestRate}%`],
    ['Loan Term', `${state.loanTerm} yrs`],
    ['Loan Amount', fmt$(outputs.loanAmount)],
  ];
  const startY = y;
  leftRows.forEach(([label, val], i) => {
    row(doc, label, val, MARGIN, y, colW, i % 2 === 1);
    y += 7;
  });

  let ry = startY;
  sectionHeader(doc, 'Income & Expenses', MARGIN + colW + 5, ry - 7, colW);
  const rightRows: [string, string][] = [
    ['Rent / Unit', fmt$(state.rentPerUnit)],
    ['Number of Units', String(state.numberOfUnits)],
    ['Vacancy Rate', `${state.vacancyRate}%`],
    ['Property Taxes', fmt$(state.propertyTaxes)],
    ['Insurance', fmt$(state.insurance)],
    ['Maintenance / CapEx', fmt$(state.maintenanceCapex)],
    ['Mgmt Fee', state.isDIY ? 'DIY (waived)' : `${state.propertyManagementFee}%`],
  ];
  rightRows.forEach(([label, val], i) => {
    row(doc, label, val, MARGIN + colW + 5, ry, colW, i % 2 === 1);
    ry += 7;
  });

  y = Math.max(y, ry) + 5;

  const optionals: [string, number][] = (
    [
      ['HOA', state.hoa],
      ['Sewer', state.sewer],
      ['Water', state.water],
      ['Lawn Care', state.lawnCare],
      ['Tenant Placement', state.tenantPlacementFee],
      ['Lease Renewal Fee', state.leaseRenewalFee],
      ['Annual Tune-up', state.annualTuneupFee],
    ] as [string, number][]
  ).filter(([, v]) => v > 0);

  if (optionals.length > 0) {
    sectionHeader(doc, 'Optional Expenses', MARGIN, y, CONTENT_W);
    y += 7;
    optionals.forEach(([label, val], i) => {
      row(doc, label, fmt$(val), MARGIN, y, CONTENT_W, i % 2 === 1);
      y += 7;
    });
  }

  pageFooter(doc);

  // ── Page 2: Charts ───────────────────────────────────────────
  if (chartsEl) {
    // Temporarily force white background for accurate capture
    const prevBg = chartsEl.style.backgroundColor;
    chartsEl.style.backgroundColor = '#ffffff';

    const canvas = await html2canvas(chartsEl, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
    });

    chartsEl.style.backgroundColor = prevBg;

    const imgData = canvas.toDataURL('image/png');
    const imgAspect = canvas.height / canvas.width;
    const imgW = CONTENT_W;
    const imgH = imgW * imgAspect;

    doc.addPage();
    pageHeader(doc, 'CHARTS & PROJECTIONS');

    const chartStartY = 33;
    const availH = PAGE_H - chartStartY - 16; // leave room for footer

    if (imgH <= availH) {
      doc.addImage(imgData, 'PNG', MARGIN, chartStartY, imgW, imgH);
    } else {
      // Scale down to fit the page
      const scale = availH / imgH;
      doc.addImage(imgData, 'PNG', MARGIN, chartStartY, imgW * scale, availH);
    }

    pageFooter(doc);
  }

  doc.save(`deal-wise-rent-analysis-${new Date().toISOString().slice(0, 10)}.pdf`);
}
