import { useCalculator } from '@/hooks/useCalculator';
import { KPIDashboard } from './KPIDashboard';
import { InputForm } from './InputForm';
import { KeyMetricsPanel } from './KeyMetricsPanel';
import { Charts } from './Charts';
import { PropertyImport } from './PropertyImport';
import { Share2, Save, Sparkles, FileDown, Zap, ChevronDown, TrendingUp, Shield, Cpu } from 'lucide-react';
import { AIDealAnalysis } from './AIDealAnalysis';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { exportDealPdf } from '@/lib/exportPdf';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { useState, useRef } from 'react';
import { AdUnit } from './AdUnit';

interface CalculatorTabProps {
  calculator: ReturnType<typeof useCalculator>;
  onSave: (name: string) => void;
  onOpenCoach: () => void;
}

const trustBadges = [
  { icon: Cpu,       text: 'AI-Powered Analysis' },
  { icon: Shield,    text: 'Free, No Sign-Up' },
  { icon: TrendingUp, text: '3 Investment Scenarios' },
];

const socialProof = [
  { value: '50K+', label: 'Properties Analyzed' },
  { value: '100%', label: 'Free Forever' },
  { value: '3',    label: 'AI Scenarios per Deal' },
];

export function CalculatorTab({ calculator, onSave, onOpenCoach }: CalculatorTabProps) {
  const { state, outputs, updateField } = calculator;
  const [saveOpen, setSaveOpen] = useState(false);
  const [saveName, setSaveName] = useState('');
  const [exporting, setExporting] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<{ address: string; propertyData: any } | null>(null);
  const chartsRef = useRef<HTMLDivElement>(null);
  const calculatorRef = useRef<HTMLDivElement>(null);

  const handleExportPdf = async () => {
    setExporting(true);
    try {
      await exportDealPdf(state, outputs, chartsRef.current);
    } finally {
      setExporting(false);
    }
  };

  const handleShare = () => {
    const text = `Deal Wise Rent Analysis
━━━━━━━━━━━━━━━
Purchase Price: $${state.purchasePrice.toLocaleString()}
Down Payment: ${state.downPaymentPercent}% ($${outputs.downPaymentAmount.toLocaleString()})
Loan Amount: $${outputs.loanAmount.toLocaleString()}
Monthly Rent: $${(state.rentPerUnit * state.numberOfUnits).toLocaleString()}
Vacancy: ${state.vacancyRate}%

Results:
Monthly Cash Flow: $${outputs.monthlyCashFlow.toFixed(0)}
CoC ROI: ${outputs.cashOnCashROI.toFixed(2)}%
Cap Rate: ${outputs.capRate.toFixed(2)}%
Total ROI: ${outputs.totalROI.toFixed(2)}%
Deal Rating: ${outputs.dealRating}

Generated by Deal Wise Rent`;

    navigator.clipboard.writeText(text)
      .then(() => toast.success('Analysis copied to clipboard!'))
      .catch(() => toast.error('Could not copy to clipboard'));
  };

  const handleSave = () => {
    if (!saveName.trim()) return;
    onSave(saveName.trim());
    setSaveOpen(false);
    setSaveName('');
    toast.success('Calculation saved!');
  };

  return (
    <>
    {/* AI Deal Analysis — rendered at root so fixed overlay escapes backdrop-filter parents */}
    {aiAnalysis && (
      <AIDealAnalysis
        address={aiAnalysis.address}
        propertyData={aiAnalysis.propertyData}
        updateField={updateField}
        onClose={() => setAiAnalysis(null)}
      />
    )}

    <div className="flex flex-col">

      {/* ═══════════════════════════════════════════
          HERO SECTION
      ═══════════════════════════════════════════ */}
      <section className="hero-bg relative overflow-hidden pb-14 pt-10 md:pt-16">

        {/* Dot grid texture */}
        <div className="dot-grid absolute inset-0 opacity-40 pointer-events-none" />

        <div className="relative max-w-3xl mx-auto px-4 md:px-6 text-center">

          {/* AI badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border text-sm font-semibold mb-6 animate-float-up animate-pulse-glow"
            style={{
              background: 'hsl(263 80% 58% / 0.08)',
              borderColor: 'hsl(263 80% 58% / 0.25)',
              color: 'hsl(263 80% 52%)',
            }}>
            <Zap className="w-3.5 h-3.5" />
            One-Click AI Deal Analysis
            <Sparkles className="w-3.5 h-3.5" />
          </div>

          {/* Headline */}
          <h1 className="text-[2.25rem] sm:text-5xl md:text-[3.5rem] font-black leading-[1.08] tracking-tight text-foreground mb-4 animate-float-up"
            style={{ animationDelay: '60ms' }}>
            Analyze Any Rental<br />
            Property with AI —{' '}
            <span className="gradient-text">Instantly.</span>
          </h1>

          {/* Subheadline */}
          <p className="text-base md:text-lg text-muted-foreground max-w-xl mx-auto mb-8 leading-relaxed animate-float-up"
            style={{ animationDelay: '120ms' }}>
            Paste a Zillow link or type an address. Our AI pulls purchase price,
            estimated rent, taxes, and 3 investment scenarios — in seconds.
          </p>

          {/* PropertyImport — floating card in hero */}
          <div className="text-left glass rounded-2xl overflow-hidden animate-float-up"
            style={{ animationDelay: '180ms' }}>
            <PropertyImport
              updateField={updateField}
              onOpenAiAnalysis={(address, propertyData) => setAiAnalysis({ address, propertyData })}
            />
          </div>

          {/* Trust badges */}
          <div className="flex flex-wrap items-center justify-center gap-2.5 mt-6 animate-float-up"
            style={{ animationDelay: '240ms' }}>
            {trustBadges.map(({ icon: Icon, text }) => (
              <div key={text} className="stat-badge">
                <Icon className="w-3 h-3" />
                {text}
              </div>
            ))}
          </div>

          {/* Scroll hint */}
          <button
            onClick={() => calculatorRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}
            className="mt-8 inline-flex flex-col items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors group"
          >
            <span>Or use the manual calculator below</span>
            <ChevronDown className="w-4 h-4 group-hover:translate-y-0.5 transition-transform" />
          </button>
        </div>
      </section>

      {/* ═══════════════════════════════════════════
          SOCIAL PROOF STRIP
      ═══════════════════════════════════════════ */}
      <div className="border-y border-border/60 bg-muted/30">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center justify-around gap-4">
          {socialProof.map(({ value, label }) => (
            <div key={label} className="text-center">
              <p className="text-xl font-black text-foreground leading-none">{value}</p>
              <p className="text-[11px] text-muted-foreground font-medium mt-0.5">{label}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ═══════════════════════════════════════════
          INVESTMENT CALCULATOR SECTION
      ═══════════════════════════════════════════ */}
      <div ref={calculatorRef} className="max-w-7xl mx-auto w-full px-4 md:px-6 py-8 space-y-6">

        {/* Section header */}
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div>
            <h2 className="text-lg md:text-xl font-black text-foreground">Investment Calculator</h2>
            <p className="text-xs text-muted-foreground mt-0.5">Tune inputs below to model your deal</p>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={onOpenCoach}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-semibold border transition-all hover:shadow-sm"
              style={{
                background: 'hsl(263 80% 58% / 0.08)',
                borderColor: 'hsl(263 80% 58% / 0.25)',
                color: 'hsl(263 80% 52%)',
              }}
            >
              <Sparkles className="w-3.5 h-3.5" />
              Deal Advisor
            </button>
            <Button variant="outline" size="sm" className="rounded-full" onClick={handleExportPdf} disabled={exporting}>
              <FileDown className="w-3.5 h-3.5 mr-1.5" />
              {exporting ? 'Exporting…' : 'Export PDF'}
            </Button>
            <Button variant="outline" size="sm" className="rounded-full" onClick={handleShare}>
              <Share2 className="w-3.5 h-3.5 mr-1.5" /> Share
            </Button>
            <Button size="sm" className="rounded-full btn-gradient border-0" onClick={() => setSaveOpen(true)}>
              <Save className="w-3.5 h-3.5 mr-1.5" /> Save
            </Button>
          </div>
        </div>

        {/* KPI Dashboard */}
        <KPIDashboard outputs={outputs} isDIY={state.isDIY} onToggleDIY={v => updateField('isDIY', v)} />

        {/* Two Column: Form + Metrics */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          <div className="lg:col-span-2">
            <InputForm state={state} updateField={updateField} />
          </div>
          <div>
            <KeyMetricsPanel outputs={outputs} />
          </div>
        </div>

        {/* Ad */}
        <AdUnit slot="7384159260" format="horizontal" className="my-1" />

        {/* Charts */}
        <div ref={chartsRef}>
          <Charts outputs={outputs} appreciationRate={state.appreciationRate} />
        </div>

        {/* Ad */}
        <AdUnit slot="7384159260" format="rectangle" className="mt-2" />
      </div>

      {/* Save Dialog */}
      <Dialog open={saveOpen} onOpenChange={setSaveOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Save Calculation</DialogTitle>
          </DialogHeader>
          <input
            type="text"
            maxLength={60}
            value={saveName}
            onChange={e => setSaveName(e.target.value)}
            placeholder="e.g. 123 Main St — 3BR Duplex"
            className="w-full h-10 rounded-lg border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
            onKeyDown={e => e.key === 'Enter' && handleSave()}
            autoFocus
          />
          <DialogFooter>
            <Button variant="outline" className="rounded-full" onClick={() => setSaveOpen(false)}>Cancel</Button>
            <Button className="rounded-full btn-gradient border-0" onClick={handleSave} disabled={!saveName.trim()}>Save Deal</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
    </>
  );
}
